//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innlegget er nå slettet.
        /// </summary>
        internal static string AdminGuestbookDeleted {
            get {
                return ResourceManager.GetString("AdminGuestbookDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern.
        /// </summary>
        internal static string AdminGuestbookOutputDelete {
            get {
                return ResourceManager.GetString("AdminGuestbookOutputDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktinfo.
        /// </summary>
        internal static string AdminProductInputAdd {
            get {
                return ResourceManager.GetString("AdminProductInputAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varen ble lagret OK.
        /// </summary>
        internal static string AdminProductInputAdded {
            get {
                return ResourceManager.GetString("AdminProductInputAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string AdminProductInputCancel {
            get {
                return ResourceManager.GetString("AdminProductInputCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string AdminProductInputCategory {
            get {
                return ResourceManager.GetString("AdminProductInputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voksen.
        /// </summary>
        internal static string AdminProductInputCategoryAdult {
            get {
                return ResourceManager.GetString("AdminProductInputCategoryAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barn.
        /// </summary>
        internal static string AdminProductInputCategoryChild {
            get {
                return ResourceManager.GetString("AdminProductInputCategoryChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Ny kategori.
        /// </summary>
        internal static string AdminProductInputCategoryExText {
            get {
                return ResourceManager.GetString("AdminProductInputCategoryExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varen er nå slettet.
        /// </summary>
        internal static string AdminProductInputDeleted {
            get {
                return ResourceManager.GetString("AdminProductInputDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer produktinfo.
        /// </summary>
        internal static string AdminProductInputEdit {
            get {
                return ResourceManager.GetString("AdminProductInputEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AdminProductInputFabric {
            get {
                return ResourceManager.GetString("AdminProductInputFabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Ull (superwash).
        /// </summary>
        internal static string AdminProductInputFabricExText {
            get {
                return ResourceManager.GetString("AdminProductInputFabricExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilde.
        /// </summary>
        internal static string AdminProductInputImage {
            get {
                return ResourceManager.GetString("AdminProductInputImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For endring, velg nytt bilde..
        /// </summary>
        internal static string AdminProductInputImageInfo {
            get {
                return ResourceManager.GetString("AdminProductInputImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildetekst (detaljside).
        /// </summary>
        internal static string AdminProductInputLongText {
            get {
                return ResourceManager.GetString("AdminProductInputLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Her kan du skrive en sjempelaaang tekst som sier noe om hvor fin denne kjolen egentlig er.
        ///
        ///Du kan også dele opp tekst i flere linjer..
        /// </summary>
        internal static string AdminProductInputLongTextExText {
            get {
                return ResourceManager.GetString("AdminProductInputLongTextExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris.
        /// </summary>
        internal static string AdminProductInputPrice {
            get {
                return ResourceManager.GetString("AdminProductInputPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. 1200.
        /// </summary>
        internal static string AdminProductInputPriceExText {
            get {
                return ResourceManager.GetString("AdminProductInputPriceExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til.
        /// </summary>
        internal static string AdminProductInputSave {
            get {
                return ResourceManager.GetString("AdminProductInputSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildetekst (listeside).
        /// </summary>
        internal static string AdminProductInputShortText {
            get {
                return ResourceManager.GetString("AdminProductInputShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Fin brun kjole!.
        /// </summary>
        internal static string AdminProductInputShortTextExText {
            get {
                return ResourceManager.GetString("AdminProductInputShortTextExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Størrelse.
        /// </summary>
        internal static string AdminProductInputSize {
            get {
                return ResourceManager.GetString("AdminProductInputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerstatus.
        /// </summary>
        internal static string AdminProductInputStock {
            get {
                return ResourceManager.GetString("AdminProductInputStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittel.
        /// </summary>
        internal static string AdminProductInputTitle {
            get {
                return ResourceManager.GetString("AdminProductInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Brun kjole.
        /// </summary>
        internal static string AdminProductInputTitleExText {
            get {
                return ResourceManager.GetString("AdminProductInputTitleExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern.
        /// </summary>
        internal static string AdminProductOutputDelete {
            get {
                return ResourceManager.GetString("AdminProductOutputDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        internal static string AdminProductOutputEdit {
            get {
                return ResourceManager.GetString("AdminProductOutputEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string AdminProductOutputSizeAdult {
            get {
                return ResourceManager.GetString("AdminProductOutputSizeAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string AdminProductOutputSizeChild {
            get {
                return ResourceManager.GetString("AdminProductOutputSizeChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/V.
        /// </summary>
        internal static string AdminProductOutputSizeChildAdult {
            get {
                return ResourceManager.GetString("AdminProductOutputSizeChildAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lager status.
        /// </summary>
        internal static string AdminProductOutputStock {
            get {
                return ResourceManager.GetString("AdminProductOutputStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists.&lt;br /&gt;Your file was saved as .
        /// </summary>
        internal static string AdminProductUploadFileExist {
            get {
                return ResourceManager.GetString("AdminProductUploadFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file was uploaded successfully..
        /// </summary>
        internal static string AdminProductUploadFileOk {
            get {
                return ResourceManager.GetString("AdminProductUploadFileOk", resourceCulture);
            }
        }
    }
}
