//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class rrart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rrart() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.rrart", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;a href=&quot;Default.aspx&quot;&gt;Forside&lt;/a&gt;&lt;/b&gt; - Om meg.
        /// </summary>
        internal static string AboutMeBreadCrumb {
            get {
                return ResourceManager.GetString("AboutMeBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Jeg er bosatt på Nesbyen i Hallingdal sammen med min mann og yngste sønn. Nå er jeg ansatt i Nes Kommune hvor jeg jobber som omsorgsarbeider i en deltidsstilling.&lt;/p&gt;&lt;p&gt;Maling har jeg som hobby. For noen år siden var jeg inne i en periode av livet hvor jeg trengte å gi uttrykk for en del følelser og tanker som var sentralt i livet mitt akkurat da. Malingen ble en uttrykksform og den gir meg energi og inspirasjon. Inspirasjonen henter jeg fra opplevelser, drømmer, stemninger og andre bilder. Jeg prøver å  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutMeInfo {
            get {
                return ResourceManager.GetString("AboutMeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innlegget er nå slettet.
        /// </summary>
        internal static string AdminGuestbookDeleted {
            get {
                return ResourceManager.GetString("AdminGuestbookDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern.
        /// </summary>
        internal static string AdminGuestbookOutputDelete {
            get {
                return ResourceManager.GetString("AdminGuestbookOutputDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktinfo.
        /// </summary>
        internal static string AdminProductInputAdd {
            get {
                return ResourceManager.GetString("AdminProductInputAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varen ble lagret OK.
        /// </summary>
        internal static string AdminProductInputAdded {
            get {
                return ResourceManager.GetString("AdminProductInputAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string AdminProductInputCancel {
            get {
                return ResourceManager.GetString("AdminProductInputCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        internal static string AdminProductInputCategory {
            get {
                return ResourceManager.GetString("AdminProductInputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voksen.
        /// </summary>
        internal static string AdminProductInputCategoryAdult {
            get {
                return ResourceManager.GetString("AdminProductInputCategoryAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barn.
        /// </summary>
        internal static string AdminProductInputCategoryChild {
            get {
                return ResourceManager.GetString("AdminProductInputCategoryChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Ny kategori.
        /// </summary>
        internal static string AdminProductInputCategoryExText {
            get {
                return ResourceManager.GetString("AdminProductInputCategoryExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varen er nå slettet.
        /// </summary>
        internal static string AdminProductInputDeleted {
            get {
                return ResourceManager.GetString("AdminProductInputDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer produktinfo.
        /// </summary>
        internal static string AdminProductInputEdit {
            get {
                return ResourceManager.GetString("AdminProductInputEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris må angis med tallene 0-9..
        /// </summary>
        internal static string AdminProductInputErrorPrice {
            get {
                return ResourceManager.GetString("AdminProductInputErrorPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AdminProductInputFabric {
            get {
                return ResourceManager.GetString("AdminProductInputFabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Ull (superwash).
        /// </summary>
        internal static string AdminProductInputFabricExText {
            get {
                return ResourceManager.GetString("AdminProductInputFabricExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilde.
        /// </summary>
        internal static string AdminProductInputImage {
            get {
                return ResourceManager.GetString("AdminProductInputImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For endring, velg nytt bilde..
        /// </summary>
        internal static string AdminProductInputImageInfo {
            get {
                return ResourceManager.GetString("AdminProductInputImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildetekst (detaljside).
        /// </summary>
        internal static string AdminProductInputLongText {
            get {
                return ResourceManager.GetString("AdminProductInputLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Her kan du skrive en sjempelaaang tekst som sier noe om hvor fin denne kjolen egentlig er.
        ///
        ///Du kan også dele opp tekst i flere linjer..
        /// </summary>
        internal static string AdminProductInputLongTextExText {
            get {
                return ResourceManager.GetString("AdminProductInputLongTextExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris.
        /// </summary>
        internal static string AdminProductInputPrice {
            get {
                return ResourceManager.GetString("AdminProductInputPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. 1200.
        /// </summary>
        internal static string AdminProductInputPriceExText {
            get {
                return ResourceManager.GetString("AdminProductInputPriceExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til.
        /// </summary>
        internal static string AdminProductInputSave {
            get {
                return ResourceManager.GetString("AdminProductInputSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildetekst (listeside).
        /// </summary>
        internal static string AdminProductInputShortText {
            get {
                return ResourceManager.GetString("AdminProductInputShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Mål: 1 x 1 cm.
        /// </summary>
        internal static string AdminProductInputShortTextExText {
            get {
                return ResourceManager.GetString("AdminProductInputShortTextExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Størrelse.
        /// </summary>
        internal static string AdminProductInputSize {
            get {
                return ResourceManager.GetString("AdminProductInputSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagerstatus.
        /// </summary>
        internal static string AdminProductInputStock {
            get {
                return ResourceManager.GetString("AdminProductInputStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittel.
        /// </summary>
        internal static string AdminProductInputTitle {
            get {
                return ResourceManager.GetString("AdminProductInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eks. Nattsvermer.
        /// </summary>
        internal static string AdminProductInputTitleExText {
            get {
                return ResourceManager.GetString("AdminProductInputTitleExText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern.
        /// </summary>
        internal static string AdminProductOutputDelete {
            get {
                return ResourceManager.GetString("AdminProductOutputDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        internal static string AdminProductOutputEdit {
            get {
                return ResourceManager.GetString("AdminProductOutputEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string AdminProductOutputSizeAdult {
            get {
                return ResourceManager.GetString("AdminProductOutputSizeAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string AdminProductOutputSizeChild {
            get {
                return ResourceManager.GetString("AdminProductOutputSizeChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/V.
        /// </summary>
        internal static string AdminProductOutputSizeChildAdult {
            get {
                return ResourceManager.GetString("AdminProductOutputSizeChildAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lager status.
        /// </summary>
        internal static string AdminProductOutputStock {
            get {
                return ResourceManager.GetString("AdminProductOutputStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists.&lt;br /&gt;Your file was saved as .
        /// </summary>
        internal static string AdminProductUploadFileExist {
            get {
                return ResourceManager.GetString("AdminProductUploadFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file was uploaded successfully..
        /// </summary>
        internal static string AdminProductUploadFileOk {
            get {
                return ResourceManager.GetString("AdminProductUploadFileOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomull.
        /// </summary>
        internal static string ColorMap1 {
            get {
                return ResourceManager.GetString("ColorMap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomull_lin.
        /// </summary>
        internal static string ColorMap2 {
            get {
                return ResourceManager.GetString("ColorMap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomull_perletvinn.
        /// </summary>
        internal static string ColorMap3 {
            get {
                return ResourceManager.GetString("ColorMap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ull.
        /// </summary>
        internal static string ColorMap4 {
            get {
                return ResourceManager.GetString("ColorMap4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ull_superwash.
        /// </summary>
        internal static string ColorMap5 {
            get {
                return ResourceManager.GetString("ColorMap5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamgarn.
        /// </summary>
        internal static string ColorMap6 {
            get {
                return ResourceManager.GetString("ColorMap6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;a href=&quot;Default.aspx&quot;&gt;Forside&lt;/a&gt;&lt;/b&gt; - Fargekart.
        /// </summary>
        internal static string ColorMapBreadCrumb {
            get {
                return ResourceManager.GetString("ColorMapBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voksen.
        /// </summary>
        internal static string CommonCategoryAdult {
            get {
                return ResourceManager.GetString("CommonCategoryAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barn.
        /// </summary>
        internal static string CommonCategoryChild {
            get {
                return ResourceManager.GetString("CommonCategoryChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barn/Voksen.
        /// </summary>
        internal static string CommonCategoryChildAdult {
            get {
                return ResourceManager.GetString("CommonCategoryChildAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris: .
        /// </summary>
        internal static string CommonPrice {
            get {
                return ResourceManager.GetString("CommonPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        internal static string CommonPriceSuffix {
            get {
                return ResourceManager.GetString("CommonPriceSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solgt.
        /// </summary>
        internal static string CommonStockNo {
            get {
                return ResourceManager.GetString("CommonStockNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til salgs.
        /// </summary>
        internal static string CommonStockYes {
            get {
                return ResourceManager.GetString("CommonStockYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3540 Nesbyen.
        /// </summary>
        internal static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;a href=&quot;Default.aspx&quot;&gt;Forside&lt;/a&gt;&lt;/b&gt; - Kontakt.
        /// </summary>
        internal static string ContactBreadCrumb {
            get {
                return ResourceManager.GetString("ContactBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rdraget@hotmail.com.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker du å bestille noen av produktene kan jeg kontaktes på telefon eller mail:.
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roselind Risan Draget.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95173624.
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultBreadCrumb {
            get {
                return ResourceManager.GetString("DefaultBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;DE FEM FRIHETER&lt;/p&gt;&lt;p&gt;Friheten til å se og høre det som er&lt;br /&gt;isteden for det som burde være, var&lt;br /&gt;eller kommer til å bli.&lt;/p&gt;&lt;p&gt;Friheten til å føle som du gjør&lt;br /&gt;isteden for det du burde.&lt;/p&gt;&lt;p&gt;Friheten til å si det du tenker og føler&lt;br /&gt;isteden for det du burde tenke og føle.&lt;/p&gt;&lt;p&gt;Friheten til å be om det du ønsker&lt;br /&gt;isteden for å vente og se om du får det.&lt;/p&gt;&lt;p&gt;Friheten til å ta sjanser på egne vegne&lt;br /&gt;isteden for alltid å være på den sikre siden.&lt;/p&gt;&lt;p&gt;Virginia Satir&lt;/p&gt;.
        /// </summary>
        internal static string DefaultInfoText {
            get {
                return ResourceManager.GetString("DefaultInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Galleri S9 (Oslo) 2011.
        /// </summary>
        internal static string Exhibitions1 {
            get {
                return ResourceManager.GetString("Exhibitions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Galleri Nystugu (Nesbyen) 2010.
        /// </summary>
        internal static string Exhibitions2 {
            get {
                return ResourceManager.GetString("Exhibitions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Ringerike Kultursenter 2010.
        /// </summary>
        internal static string Exhibitions3 {
            get {
                return ResourceManager.GetString("Exhibitions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Ål Kulturhus 2010.
        /// </summary>
        internal static string Exhibitions4 {
            get {
                return ResourceManager.GetString("Exhibitions4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Vestfoldmessen 2009.
        /// </summary>
        internal static string Exhibitions5 {
            get {
                return ResourceManager.GetString("Exhibitions5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Kjerringtorget 2008.
        /// </summary>
        internal static string Exhibitions6 {
            get {
                return ResourceManager.GetString("Exhibitions6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Vikersund 2007.
        /// </summary>
        internal static string Exhibitions7 {
            get {
                return ResourceManager.GetString("Exhibitions7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Glesvær Cafè Sotra 2011.
        /// </summary>
        internal static string Exhibitions8 {
            get {
                return ResourceManager.GetString("Exhibitions8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstilling Galleri Gol 2011.
        /// </summary>
        internal static string Exhibitions9 {
            get {
                return ResourceManager.GetString("Exhibitions9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;a href=&quot;Default.aspx&quot;&gt;Forside&lt;/a&gt;&lt;/b&gt; - Utstillinger.
        /// </summary>
        internal static string ExhibitionsBreadCrumb {
            get {
                return ResourceManager.GetString("ExhibitionsBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlagte utstillinger 2012:&lt;br/&gt;Galleri Nystugu høst 2012.
        /// </summary>
        internal static string ExhibitionsFurtherPlans {
            get {
                return ResourceManager.GetString("ExhibitionsFurtherPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;a href=&quot;Default.aspx&quot;&gt;Forside&lt;/a&gt;&lt;/b&gt; - Gjestebok.
        /// </summary>
        internal static string GuestbookBreadCrumb {
            get {
                return ResourceManager.GetString("GuestbookBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        internal static string GuestbookEmail {
            get {
                return ResourceManager.GetString("GuestbookEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv innlegg.
        /// </summary>
        internal static string GuestbookEntryTitle {
            get {
                return ResourceManager.GetString("GuestbookEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        internal static string GuestbookName {
            get {
                return ResourceManager.GetString("GuestbookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til innlegg.
        /// </summary>
        internal static string GuestbookSave {
            get {
                return ResourceManager.GetString("GuestbookSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trykk på smiley for å inkludere i teksten - bildet vil bli synlig etter at innlegget er lagt til..
        /// </summary>
        internal static string GuestbookSmileys {
            get {
                return ResourceManager.GetString("GuestbookSmileys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskjed.
        /// </summary>
        internal static string GuestbookText {
            get {
                return ResourceManager.GetString("GuestbookText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om meg.
        /// </summary>
        internal static string MasterPageAboutMeLink {
            get {
                return ResourceManager.GetString("MasterPageAboutMeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fargekart.
        /// </summary>
        internal static string MasterPageColorMapLink {
            get {
                return ResourceManager.GetString("MasterPageColorMapLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string MasterPageContactLink {
            get {
                return ResourceManager.GetString("MasterPageContactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utstillinger.
        /// </summary>
        internal static string MasterPageExhibitionsLink {
            get {
                return ResourceManager.GetString("MasterPageExhibitionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjestebok.
        /// </summary>
        internal static string MasterPageGuestbookLink {
            get {
                return ResourceManager.GetString("MasterPageGuestbookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roselind Risan Art.
        /// </summary>
        internal static string MasterPageLogoText {
            get {
                return ResourceManager.GetString("MasterPageLogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkter.
        /// </summary>
        internal static string MasterPageProductLink {
            get {
                return ResourceManager.GetString("MasterPageProductLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;a href=&quot;Default.aspx&quot;&gt;Forside&lt;/a&gt;&lt;/b&gt; - &lt;b&gt;&lt;a href=&quot;ProductList.aspx&quot;&gt;Produktliste&lt;/a&gt;&lt;/b&gt; - Produktdetalj.
        /// </summary>
        internal static string ProductDetailBreadCrumb {
            get {
                return ResourceManager.GetString("ProductDetailBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trykk på bildet for å se det i full størrelse..
        /// </summary>
        internal static string ProductDetailPicture {
            get {
                return ResourceManager.GetString("ProductDetailPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varen finnes i størrelse: .
        /// </summary>
        internal static string ProductDetailSize {
            get {
                return ResourceManager.GetString("ProductDetailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktet er laget av .
        /// </summary>
        internal static string ProductDetailWash {
            get {
                return ResourceManager.GetString("ProductDetailWash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maskinvask 60 grader. Henges til tørk..
        /// </summary>
        internal static string ProductDetailWash_Bomull {
            get {
                return ResourceManager.GetString("ProductDetailWash_Bomull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maskinvask 60 grader. Henges til tørk..
        /// </summary>
        internal static string ProductDetailWash_Bomull_lin {
            get {
                return ResourceManager.GetString("ProductDetailWash_Bomull_lin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maskinvask 60 grader. Henges til tørk..
        /// </summary>
        internal static string ProductDetailWash_Bomull_perletvinn {
            get {
                return ResourceManager.GetString("ProductDetailWash_Bomull_perletvinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Håndvask 30 grader. Tørkes flatt..
        /// </summary>
        internal static string ProductDetailWash_Kamgarn {
            get {
                return ResourceManager.GetString("ProductDetailWash_Kamgarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Håndvask 30 grader. Tørkes flatt..
        /// </summary>
        internal static string ProductDetailWash_Ull {
            get {
                return ResourceManager.GetString("ProductDetailWash_Ull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maskinvask 40 grader ullprogram. Tørkes flatt..
        /// </summary>
        internal static string ProductDetailWash_Ull_superwash {
            get {
                return ResourceManager.GetString("ProductDetailWash_Ull_superwash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;a href=&quot;Default.aspx&quot;&gt;Forside&lt;/a&gt;&lt;/b&gt; - Produktliste.
        /// </summary>
        internal static string ProductListBreadCrumb {
            get {
                return ResourceManager.GetString("ProductListBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall produkter: .
        /// </summary>
        internal static string ProductListNumberOfProducts {
            get {
                return ResourceManager.GetString("ProductListNumberOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trykk her for å&lt;br /&gt; starte fremvisning.
        /// </summary>
        internal static string ProductListSlideshow {
            get {
                return ResourceManager.GetString("ProductListSlideshow", resourceCulture);
            }
        }
    }
}
